services:
  api:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - stripe-db

  stripe-db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file: .env

  redis:
    image: redis/redis-stack:latest
    restart: always
    # environment:
      # - REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redis_data_dev:/var/lib/redis/data
    ports:
      - "6379:6379"
      - "8001:8001"
    env_file: .env

  celery:
    build:
      context: .
    command: celery -A tasks.app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file: .env

volumes:
  postgres_data_dev:
  redis_data_dev:
