"""empty message

Revision ID: 005bf460cdbe
Revises: 351b8706d85c
Create Date: 2025-07-28 18:13:59.322883

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from models.subscription import SubscriptionTier


# revision identifiers, used by Alembic.
revision: str = "005bf460cdbe"
down_revision: Union[str, Sequence[str], None] = "351b8706d85c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscriptions",
        sa.Column(
            "tier",
            sa.String,
            nullable=False,
            server_default=SubscriptionTier.free.value,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscriptions", "tier")
    # ### end Alembic commands ###
