"""empty message

Revision ID: 533da00ce397
Revises: 2e66d087b702
Create Date: 2025-07-03 15:58:35.914682

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "533da00ce397"
down_revision: Union[str, Sequence[str], None] = "2e66d087b702"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscriptions",
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, server_default=sa.text("now()")
        ),
    )
    op.add_column(
        "subscriptions",
        sa.Column(
            "updated_at", sa.DateTime(), nullable=False, server_default=sa.text("now()")
        ),
    )
    op.add_column(
        "subscriptions", sa.Column("canceled_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscriptions", "canceled_at")
    op.drop_column("subscriptions", "updated_at")
    op.drop_column("subscriptions", "created_at")
    # ### end Alembic commands ###
